name: ProjectManager
version: '${project.version}'
main: com.njdaeger.projectmanager.ProjectManager
api-version: 1.17
depend: [ AuthenticationHub ]
authors: [ NJDaeger ]
description: Project management platform for creative minecraft servers
